       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO-WORLD.
       
       ENVIRONMENT DIVISION.
       
       DATA DIVISION.
      ** FIXME
       PROCEDURE DIVISION.
       000-MAIN-PROCEDURE.
           DISPLAY "HELLO WORLD!".
           STOP RUN.
